config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  resources :sites
  resources :posts

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advert.rb
class Advert
  include Mongoid::Document
  field :name, type: String
  field :ad_code, type: String
  field :start_date, type: String
  field :end_date, type: String
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::Validations
  field :title, type: String
  field :content, type: String
  field :featuredmedia, type: String
  field :post_type, type: String
  field :source_link, type: String
  field :site_id, type: String
  field :author_name, type: String
  field :author_avatar, type: String
  field :tags
  field :category, type: String
  field :author_avatars
  field :author, type: String
  field :created_at, type: String
  field :updated_at, type: String

  index({ title: 1 }, { unique: true })

  before_create :created_at_fix
  before_update :updated_at_fix

  def created_at_fix
    self.created_at = Time.now
  end
  def updated_at_fix
    self.pdated_at = Time.now
  end

  def sites
    Site.where(id: self.site_id)
  end
  
end

app/models/site.rb
class Site
  include Mongoid::Document
  field :name, type: String
  field :avatar, type: String
  field :baseUrl, type: String


  def created_at
    "time"
  end
  def updated_at
    "last updated"
  end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.all
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
  end

  # GET /adverts/new
  def new
    @advert = Advert.new
  end

  # GET /adverts/1/edit
  def edit
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(advert_params)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: 'Advert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params.require(:advert).permit(:name, :ad_code, :start_date, :end_date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order("id DESC").paginate(:page => params[:page])
  end

  def show
    @relatedsamecontents = Post.all.limit(3)
    
  end

  def new
    @post = Post.new
  end

  def edit
  end


  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :created_at, :featuredmedia, :post_type, :source_link, :site_id)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  def index
    @sites = Site.order("_id DESC")
  end

  def show
  end

  def new
    @site = Site.new
  end

  def edit
  end

  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_site
      @site = Site.find(params[:id])
    end

    def site_params
      params.require(:site).permit(:name, :avatar, :baseUrl)
    end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def title(page_title)
        content_for(:title) { page_title }
    end

    def adverts_small
        Advert.skip(rand(Advert.count)).first
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/adverts/_form.html.erb
<%= form_with(model: advert, local: true) do |form| %>
  <% if advert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advert.errors.count, "error") %> prohibited this advert from being saved:</h2>

      <ul>
      <% advert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ad_code %>
    <%= form.text_area :ad_code %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.text_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.text_field :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adverts/edit.html.erb
<div class="container">
    <h1>Editing Advert</h1>

    <%= render 'form', advert: @advert %>

    <%= link_to 'Show', @advert %> |
    <%= link_to 'Back', adverts_path %>
</div>

app/views/adverts/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Adverts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ad code</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adverts.each do |advert| %>
      <tr>
        <td><%= advert.name %></td>
        <td><%= advert.ad_code %></td>
        <td><%= advert.start_date %></td>
        <td><%= advert.end_date %></td>
        <td><%= link_to 'Show', advert %></td>
        <td><%= link_to 'Edit', edit_advert_path(advert) %></td>
        <td><%= link_to 'Destroy', advert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advert', new_advert_path %>

</div>

app/views/adverts/new.html.erb
<div class="container">
    <h1>New Advert</h1>
    <%= render 'form', advert: @advert %>
    <%= link_to 'Back', adverts_path %>
</div>

app/views/adverts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @advert.name %>
</p>

<p>
  <strong>Ad code:</strong>
  <%= @advert.ad_code %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @advert.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @advert.end_date %>
</p>

<%= link_to 'Edit', edit_advert_path(@advert) %> |
<%= link_to 'Back', adverts_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? content_for(:title) : "Manga Bunny" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://vjs.zencdn.net/7.3.0/video-js.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <aside class="navbar">
      <%= render 'navs/normal' %>
    </aside>

    <%= render 'navs/topnav' %>

    <div class="wrapper">
      <%= yield %>
      <%= render 'navs/footer' %>
    </div>

    <script src="https://vjs.zencdn.net/7.3.0/video.js"></script>
  </body>
</html>

app/views/navs/_normal.html.erb
<nav class="sideNav">
  <div class="logo">
    <a href="<%= root_path %>">漫画</a>
    <h1 class="hidden_site_name">
      Manga Bunny
    </h1>
  </div>
  <ul>
    <a href="<%= root_path %>">
      <li> </li>
    </a>

    <a href="<%= posts_path %>">
      <li> </li>
    </a>

    <a href="<%= sites_path %>">
      <li> </li>
    </a>

    <a href="<%= adverts_path %>">
      <li> </li>
    </a>

  </ul>
</nav>

app/views/navs/_topnav.html.erb
<nav>
    <div class="navbar-top">
        <div class="container">
            <ul class="row">
            
                <div class="col">
                    <div class="searchbar">
                        <input type="search" id="search" class="searchBar" placeholder="Search ...">
                    </div>
                </div>

                <div class="col">
                    <a>
                        <li>
                            Hello
                        </li>
                    </a>
                </div>
            </ul>
        </div>
    </div>
</nav>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.text_field :created_at %>
  </div>

  <div class="field">
    <%= form.label :featuredmedia %>
    <%= form.text_field :featuredmedia %>
  </div>

  <div class="field">
    <%= form.label :post_type %>
    <%= form.text_field :post_type %>
  </div>

  <div class="field">
    <%= form.label :source_link %>
    <%= form.text_field :source_link %>
  </div>

  <div class="field">
    <%= form.label :site_id %>
    <%= form.number_field :site_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_googlead.html.erb
<small><label class="sponsortext">Sponsored</label></small>
<div class="advertisment" id="advertisment">
<%= adverts_small.name %> <br>
<%= adverts_small.ad_code %> <br>
<%= adverts_small.start_date %> <br>
<%= adverts_small.end_date %>
</div>

app/views/posts/_info.html.erb
<div class="article_source">
    <div class="row">
        <div class="col">
                <div class="avatar" style="background-image: url(<%= @post.author_avatars["96"]%>)">
                </div>
                <div class="author">
                    <strong class="author_name"><%= @post.author %></strong> <br>
                    <small>
                        <strong class="source_name">
                            <% @post.sites.each do |site| %>
                                <%= site.name %>
                            <% end %>
                        </strong>
                    </small>
                </div>
        </div>
        <div class="col align-right">
                <span class="badge badge-light"><%= time_ago_in_words(@post.created_at) %></span>
        </div>
    </div>
    
</div>

app/views/posts/_postfooter.html.erb
<div class="article_footer">
      <p>
        <strong>
            source : <a href="<%= @post.source_link %>">
                <% @post.sites.each do |site| %>
                    <%= site.name%>
                <% end %>
            </a>
        </strong>
      </p>
      <hr>

      <div class="tags">
        <% @post.tags.each do |tag|%>
            <label class="badge-tags"><%= tag %></label>
        <% end %>
      </div>

      <p>
        <%# <strong>Site:</strong> %>
        <%#= @post.site_id %>
      </p>

      <%#= link_to 'Edit', edit_post_path(@post) %>
      <%#= link_to 'Back', posts_path %>
</div>

app/views/posts/_samesitecontent.html.erb
<div class="container black-bg p30">
    <div class="row">
        
        <script type="text/javascript">
            let related = <%= raw(@relatedsamecontents.to_json) %>
            console.log(related)
        </script>
        <% @relatedsamecontents.each do |related| %>
            <div class="col">
                <a href="<%= post_path(related)%>">
                    <div class="article_card">
                        <div class="featured" style="background-image: url(<%= related.featuredmedia %>)"></div>
                        <div class="card-body">
                            <h5 class="card-title">
                                <%= truncate(related.title.html_safe, length: 50, :omission => "..." , :escape => false) %>
                            </h5>
                            <label class="time_ago">
                                <%= time_ago_in_words(related.created_at) %>
                            </label>
                        </div>
                    </div>
                </a>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <h1>Posts</h1>
      <div class="row cards">

      <% @posts.each do |post| %>
        <div class="card col-md-3">
          <a href="<%= post_path(post) %>">
            <div class="boxshad">
            <div class="featured" style="background-image: url(<%= post.featuredmedia %>)"></div>
              <div class="card-body">
                <h5 class="card-title"><%= truncate(post.title.html_safe, length: 40, :omission => "" , :escape => false) %></h5>
                <p class="card-text"><small class="text-muted"><%= time_ago_in_words(post.created_at) %></small></p>
              </div>
            </div>
          </a>
        </div>
          <%#= link_to 'Edit', edit_post_path(post) %>
          <%#= link_to 'Destroy', post, method: :delete %>

      <% end %>
  </div>
  <br>

  <%#= link_to 'New Post', new_post_path %>
<%= will_paginate @posts %>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%- title "Reading #{@post.title}" %>
<div class="container">
  <div class="row">
    <div class="col-md-8 article">
      <div class="catcontainer" >
        <strong class="category"> Category </strong>
      </div>
      <h1 class="article_title">
        <%= @post.title.html_safe %>
      </h1>

      <hr>
      <%= render 'posts/info' %>
      <hr>

      <%#= image_tag @post.featuredmedia %>

      <div class="article_conetent">
        <%= @post.content.html_safe %>
      </div>

      <%= render 'posts/postfooter'%>
    </div>

    <div class="col">
      <%= render 'posts/googlead' %>
    </div>
  </div>
</div>
<div class="newgoals">
<%= render 'posts/samesitecontent' %>
</div>

app/views/sites/_form.html.erb
<%= form_with(model: site, local: true) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :baseUrl %>
    <%= form.text_field :baseUrl %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar</th>
      <th>Baseurl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.name %></td>
        <td><%= site.avatar %></td>
        <td><%= site.baseUrl %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>
</div>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @site.avatar %>
</p>

<p>
  <strong>Baseurl:</strong>
  <%= @site.baseUrl %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>